ANSWERS = [
    "crane", "slate", "trace", "stone", "plank", "brave", "crisp", "blend",
    "crave", "drape", "elbow", "flint", "gloom", "haste", "inert", "joust",
    "knack", "lusty", "mirth", "nudge", "optic", "prank", "quilt", "rivet",
    "smolt", "taunt", "usurp", "vital", "waltz", "xylem", "yearn", "zesty",
    "abyss", "blaze", "cleft", "dross", "epoch", "froth", "graft", "hunts",
    "irony", "jaunt", "knave", "lurch", "mourn", "notch", "ovary", "pivot",
    "quirk", "rogue", "snare", "tryst", "unwed", "vouch", "whelp", "oxide",
    "yeoman", "abbot", "blurt", "clasp", "dowry", "equip", "flunk", "gripe",
    "abuse", "acute", "admit", "adobe", "adult", "after", "again", "agate",
    "agile", "aging", "agony", "agree", "ahead", "aided", "aimed", "algae",
    "alibi", "alien", "align", "allay", "alloy", "aloft", "alone", "aloof",
    "aloud", "altar", "alter", "amass", "amaze", "amble", "amend", "amiss",
    "angel", "anger", "angle", "angry", "angst", "annex", "annoy", "antic",
    "anvil", "aorta", "apron", "aptly", "ardor", "arena", "argon", "arid",
    "arise", "armor", "aroma", "array", "arrow", "artsy", "ascot", "ashen",
    "askew", "atlas", "atone", "attic", "audio", "audit", "augur", "avail",
    "avian", "avoid", "awake", "award", "aware", "awful", "awoke", "azure",
    "badge", "badly", "banal", "basic", "basil", "basis", "batch", "bathe",
    "bauble", "bayou", "beach", "beard", "beast", "began", "begin", "being",
    "below", "bench", "berth", "beset", "bezel", "biome", "birch", "birth",
    "bison", "blimp", "bliss", "bloat", "block", "blood", "bloom", "blown",
    "blunt", "blurt", "boded", "bogus", "bolts", "boned", "bonus", "boost",
    "booth", "borax", "boxer", "brace", "braid", "brash", "brawn", "braze",
    "bread", "breed", "breve", "briar", "brine", "brink", "briny", "brisk",
    "broil", "brood", "brook", "broth", "brows", "brunt", "bruit", "brush",
    "bucks", "buddy", "budge", "buggy", "build", "built", "bulge", "bunny",
    "burly", "burns", "burst", "butch", "butts", "buyer", "bylaw",
    "cabin", "cache", "cadet", "camel", "candy", "cargo", "carol", "carry",
    "carve", "cedar", "cellar", "chain", "chair", "chalk", "champ", "chant",
    "chaos", "charm", "chasm", "cheap", "cheat", "check", "cheek", "cheer",
    "chess", "chest", "chief", "child", "china", "chips", "choir", "chord",
    "civic", "civil", "claim", "clamp", "clang", "clash", "class", "clean",
    "clear", "cleft", "clerk", "click", "cliff", "clink", "clip", "cloak",
    "clock", "clone", "close", "cloth", "cloud", "clown", "cluck", "clump",
    "coast", "cobra", "cocoa", "colon", "color", "comet", "comic", "coral",
    "corny", "could", "count", "court", "cover", "crack", "craft", "cramp",
    "crash", "creak", "cream", "creek", "creep", "crimp", "cross", "crowd",
    "crown", "crude", "cruel", "crush", "crust", "crypt", "cubic", "curse",
    "curve", "cycle",
    "daily", "dance", "datum", "dealt", "decay", "decry", "delay", "delta",
    "demon", "depot", "depth", "derby", "devil", "diary", "digit", "dimly",
    "disco", "ditty", "divan", "diver", "dizzy", "dodge", "dogma", "doing",
    "donor", "doted", "doubt", "dough", "draft", "drain", "drama", "drank",
    "drawl", "dread", "dream", "dress", "dried", "drift", "drill", "drink",
    "drive", "drone", "drool", "droop", "drown", "drove", "drown", "druid",
    "drunk", "dryer", "duchy", "dusky", "dusty", "dwarf", "dwell",
    "eagle", "earthy", "easel", "ebony", "edict", "eight", "eject", "elude",
    "email", "embed", "emote", "empty", "enact", "endow", "enjoy", "ensue",
    "enter", "envoy", "epoxy", "erode", "erupt", "essay", "ether", "evade",
    "event", "every", "evoke", "exact", "exert", "exile", "exist", "extol",
    "fable", "facet", "faint", "fairy", "faith", "fancy", "fatal", "fault",
    "feast", "feral", "ferry", "fetch", "fever", "fewer", "feign", "field",
    "fiend", "fiery", "fifty", "fight", "finch", "first", "fixed", "fjord",
    "flame", "flask", "fleet", "flesh", "flick", "fling", "float", "flock",
    "floor", "flora", "floss", "flour", "flown", "flute", "focal", "force",
    "forge", "forth", "found", "franc", "frank", "fraud", "fresh", "front",
    "froze", "frugal", "fungi", "funny", "furor", "fuzzy",
    "gauze", "gavel", "gaudy", "gecko", "genre", "ghost", "ghoul", "glare",
    "glass", "gleam", "glean", "glide", "glint", "globe", "gloss", "glove",
    "glyph", "gnome", "godly", "going", "golem", "gorge", "gourd", "grace",
    "grade", "grain", "grand", "grant", "grasp", "grass", "grate", "gravel",
    "graze", "greed", "greet", "grind", "groan", "groin", "grope", "gross",
    "grout", "grove", "growl", "grown", "gruel", "gruff", "grunt", "guile",
    "guise", "gulch", "gully", "gusto", "gypsy",
    "habit", "haiku", "hairy", "halve", "harsh", "hazel", "heady", "heart",
    "heavy", "hedge", "hence", "herbs", "heron", "hinge", "hippo", "hoist",
    "holly", "homer", "honey", "honor", "horde", "horse", "hotel", "hound",
    "hover", "howdy", "humid", "humor", "hurry", "husky",
    "icily", "idiom", "idiot", "igloo", "image", "impel", "inane", "incur",
    "index", "infer", "ingot", "inset", "inter", "intro", "ionic", "irate",
    "ivory",
    "jagged", "jazzy", "jewel", "joist", "joker", "jolly", "jumpy", "juror",
    "karma", "kayak", "khaki", "kitty", "kneel", "knelt", "knife", "knoll",
    "known",
    "label", "lance", "lanky", "lapel", "laser", "latch", "later", "lauds",
    "laughs", "layer", "leaky", "learn", "leapt", "leave", "ledge", "legal",
    "lemon", "level", "light", "lilac", "limbo", "linen", "liner", "liver",
    "llama", "local", "lodge", "logic", "loose", "lofty", "loopy", "lorry",
    "lotus", "lover", "lower", "lucid", "lucky", "lyric",
    "magic", "major", "maker", "manor", "maple", "march", "marry", "match",
    "maven", "mayor", "mealy", "medal", "media", "mercy", "merit", "metal",
    "midst", "mimic", "miser", "mixer", "mocha", "model", "mogul", "moldy",
    "money", "monks", "moody", "mossy", "motif", "motor", "motto", "mound",
    "mount", "mouse", "mouth", "moved", "muddy", "murky", "music", "musty",
    "nadir", "naive", "navel", "needy", "nerve", "night", "nitwit", "noble",
    "noise", "nonce", "north", "novel", "nurse", "nymph",
    "offal", "often", "olive", "onset", "opine", "orbit", "order", "ought",
    "ounce", "outdo", "outer", "outdo", "ovoid", "oxide",
    "paddy", "pagan", "paint", "panic", "papal", "parka", "parse", "pasta",
    "patch", "pause", "peace", "pearl", "penal", "penny", "perch", "peril",
    "perky", "petal", "petty", "phase", "phone", "photo", "piano", "pixel",
    "pixie", "pizza", "place", "plaid", "plain", "plant", "plaza", "plead",
    "plume", "plump", "plunk", "plush", "poach", "point", "poise", "poker",
    "polar", "poppy", "power", "press", "price", "pride", "prime", "print",
    "prism", "privy", "probe", "proof", "prose", "proud", "prune", "psalm",
    "pudgy", "pulse", "pumas", "purge", "pygmy",
    "qualm", "query", "queue", "quick", "quiet", "quota", "quote",
    "rabbi", "rabid", "rainy", "raise", "rally", "ramen", "raven", "reach",
    "ready", "realm", "rebel", "reedy", "regal", "reign", "relax", "relic",
    "repay", "repel", "resin", "retch", "retro", "rhino", "rhyme", "ridge",
    "rigid", "risky", "ritzy", "rival", "river", "robin", "rocky", "rodeo",
    "rondo", "roomy", "roost", "rouge", "rough", "round", "rouse", "royal",
    "rugby", "ruler", "runny", "rural", "rusty",
    "sadly", "saggy", "saint", "salve", "salvo", "sandy", "sappy", "savor",
    "scald", "scalp", "scaly", "scant", "scare", "scarf", "scene", "scone",
    "scoop", "scour", "scout", "scowl", "scram", "screw", "scrub", "seedy",
    "seize", "serve", "seven", "shard", "share", "shark", "sharp", "shave",
    "shawl", "sheen", "sheer", "shelf", "shell", "shift", "shine", "shirt",
    "shoal", "shock", "shore", "short", "shout", "shove", "showy", "shrub",
    "shrug", "shuck", "sight", "sigma", "silky", "silly", "sinew", "sixth",
    "sixty", "skate", "skiff", "skimp", "skull", "slant", "sleet", "slept",
    "slick", "slide", "slime", "slimy", "sling", "sloth", "slump", "slung",
    "slunk", "slurp", "small", "smash", "smear", "smell", "smite", "smoke",
    "smoky", "snack", "snaky", "snout", "snowy", "snuck", "soggy", "solar",
    "solid", "sonar", "sonic", "sorry", "south", "space", "spade", "spank",
    "spare", "spark", "spawn", "speak", "spear", "speck", "speed", "spell",
    "spend", "spice", "spicy", "spill", "spine", "spite", "split", "spoke",
    "spoof", "spook", "spoon", "spore", "sport", "spout", "spree", "sprig",
    "spunk", "squad", "squat", "squid", "squint", "stack", "staff", "staid",
    "stain", "stair", "stale", "stall", "stamp", "stand", "stank", "stark",
    "start", "stash", "stave", "stays", "stead", "steam", "steel", "steep",
    "steer", "stern", "stiff", "still", "sting", "stink", "stomp", "stood",
    "stool", "stoop", "store", "stork", "storm", "story", "stout", "stove",
    "strap", "straw", "stray", "strep", "strip", "strut", "stuck", "study",
    "stump", "stung", "stunk", "stunt", "style", "sugar", "suite", "sulky",
    "sunny", "super", "surge", "surly", "swamp", "swear", "sweat", "sweep",
    "sweet", "swept", "swill", "swoop", "synod",
    "tabby", "taboo", "tacit", "talon", "tapir", "tardy", "taste", "tasty",
    "tatty", "tawny", "teach", "teary", "tense", "tepid", "terse", "theft",
    "thief", "thing", "think", "thorn", "those", "three", "threw", "throb",
    "throw", "thumb", "thump", "tiara", "tidal", "timid", "tipsy", "tired",
    "titan", "today", "token", "torch", "total", "totem", "touch", "tough",
    "towel", "tower", "toxic", "trail", "train", "trait", "tramp", "trash",
    "trawl", "tread", "treat", "trend", "trick", "tried", "trite", "troop",
    "trout", "truck", "truly", "trump", "trunk", "truss", "truth", "tulip",
    "tuner", "turbo", "tutor", "tweak", "tweed", "twice", "twirl", "twist",
    "tying",
    "ulcer", "ultra", "unify", "union", "untie", "unzip", "upper", "urban",
    "eerie", "using", "utter",
    "vague", "valid", "valor", "value", "valve", "vapor", "vault", "veiny",
    "verge", "verse", "vicar", "video", "vigor", "viola", "viper", "viral",
    "virus", "visor", "vista", "vivid", "vixen", "vocal", "vodka", "voila",
    "vomit", "voter",
    "wacky", "wafer", "wager", "wagon", "waken", "waste", "watch", "water",
    "weary", "weave", "wedge", "weedy", "weird", "whale", "whack", "wheat",
    "wheel", "where", "which", "whiff", "while", "whirl", "whisk", "white",
    "whole", "whose", "widen", "wider", "widow", "windy", "witty", "woken",
    "woman", "women", "world", "wormy", "worst", "worth", "wrath", "wrist",
    "wrong", "wrote",
    "yacht", "yodel", "young", "yours", "youth",
    "zonal", "zombi", "zonal",
]

# Filter to exactly 5-letter words and deduplicate
ANSWERS = list(dict.fromkeys(w.lower() for w in ANSWERS if len(w) == 5))

VALID_GUESSES = set(ANSWERS)  # accept any answer word as a valid guess
